apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "clonecloud.fullname" . }}-limitrange
  labels:
    {{- include "clonecloud.labels" . | nindent 4 }}
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
