apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "clonecloud.fullname" . }}-quota
  labels:
    {{- include "clonecloud.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "15"
